### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by scorppio** [ianling/zipPy#2]
File "/content/zipPy/zipPy.py", line 18
    help='Path to FILE containing a list of Zippyshare.com URLs separated by newlines', metavar='FILE') option_parser.add_option('-d', '--dlc', action='store', dest='dlc_file',
                                                                                                                    ^
SyntaxError: invalid syntax

non of the command is working .

**Comment by ianling** [comment]
This error occurs when you attempt to run the script in python3. The script currently only works for python2.

I will update the script to work with python3.

**Comment by ianling** [comment]
Python3 support added to master branch.
